### ISSUE TITLE
Possible move to voxpupuli

### ISSUE THREAD

**Issue by cdenneen** [voxpupuli/puppet-openvmtools#12]
Mike,

I opened the following to help out if you are okay with moving. Didn't seem like you wanted to be doing module development anymore:

https://github.com/voxpupuli/plumbing/pull/198
https://github.com/voxpupuli/modulesync_config/pull/551

Let me know if you'd like to do this or not, I've opened #11 if not. (only failure is Ruby 1.8.7 which probably should be removed)

-Chris

**Comment by razorsedge** [comment]
Yes.  I am sorting out the migration steps.

**Comment by razorsedge** [comment]
@cdenneen It should be complete.

**Comment by razorsedge** [comment]
Let me know if razorsedge/puppet-vmwaretools should go over as well.

**Comment by cdenneen** [comment]
Yes please

**Comment by razorsedge** [comment]
Done.

**Comment by pillarsdotnet** [comment]
Fixed by #14 and #15
