### ISSUE TITLE
Remove https://forge.puppet.com/modules/razorsedge/openvmtools ?

### ISSUE THREAD

**Issue by stefanlasiewski** [voxpupuli/puppet-openvmtools#38]
I tried to report an issue with https://forge.puppet.com/modules/razorsedge/openvmtools and was directed here.

I assume this project is a fork of https://forge.puppet.com/modules/razorsedge/openvmtools. If that's the case, can we get someone or @razorsedge to mark the older forge version as 'deprecated' in favor of the Vox Pupuli project?

It's confusing to have two different related projects on the Forge, especially since I can't find  any formal notice that `razorsedge/openvmtools` was replaced by `puppet/openvmtools`.

![image](https://user-images.githubusercontent.com/142752/103708488-849b6600-4f65-11eb-86a0-c42ae60bc4d6.png)

**Comment by ekohl** [comment]
It would be best to file an issue for that on Puppet's JIRA, similar to https://tickets.puppetlabs.com/browse/FORGE-584. I think that's the best we can do.

**Comment by ekohl** [comment]
https://forge.puppet.com/modules/razorsedge/openvmtools already has a deprecated label.
